#!/usr/bin/php
<?php

# const
define('ROOT_DIR', dirname(__DIR__));

# autoload;
require_once("autoload.php");

# set ini;
date_default_timezone_set('Asia/Seoul');
ini_set('memory_limit','512M');

# execute script;
$script_loader = new Saseul\Common\ScriptLoader($argv);
$script_loader->main();